### ISSUE TITLE
Write protect the master branch

### ISSUE THREAD

**Issue by danielsclint** [UDST/activitysim#64]
The master branch needs to be write protected to only allow pull requests after automated testing is completed and passed.

**Comment by toliwaga** [comment]
Master branch is write protected and requires passing travis tests for pull requests. I have not enabled a coverage threshold or coverage decrease threshold because I wasn't sure I could set different thresholds for master and other branches and wanted to wait to see what kind of fluctuation in coverage we might tolerate making branches available between developers during active development. Though I guess we could set the bar pretty low (like 95%) with no problem. In any case I am getting slack notifications and of course run the tests before any commit so this is probably a less urgent issue, unless anyone has strong feelings about the right thing to do.
