### ISSUE TITLE
duplicate column definitions?

### ISSUE THREAD

**Issue by bstabler** [UDST/activitysim#72]
It seems these orca virtual column definitions 
```
@orca.column("persons_workplace")
def school_taz(persons):
    return pd.Series(1, persons.index)

@orca.column("persons")
def workplace_taz(persons):
    return pd.Series(1, persons.index)
```
are not needed in persons.py since they are added by school_location.py and workplace_location.py respectively
```
orca.add_column("persons", "workplace_taz", choices)

orca.add_column("persons", "school_taz", choices)
```

**Comment by toliwaga** [comment]
It looks like this is legacy code from before the practice of defining placeholder tables adding dependent computed column with add_dependent_columns

workplace_taz is currently required in order to satisfy the distance_to_work computed column:

```
# this use the distance skims to compute the raw distance to work from home
@orca.column("persons")
def distance_to_work(persons, distance_skim):
    return pd.Series(distance_skim.get(persons.home_taz,
                                       persons.workplace_taz),
                     index=persons.index)
```

Distance to school is not required because it is defined on "persons_school"

The orca decorator for distance_to_work should be changed to
@orca.column("persons_workplace")

That way the distance_to_work computed column will only be added to the persons table _after_ workplace_location_simulate has added the workplace_taz column to persons:

```
    orca.add_column("persons", "workplace_taz", choices)
    add_dependent_columns("persons", "persons_workplace")
```
