### ISSUE TITLE
Fastest way to access skims

### ISSUE THREAD

**Issue by fscottfoti** [UDST/activitysim#8]
@jiffyclub At some point pretty soon we'll want to diagnose the fastest way to access skims.  Given that we store the skims in OMX format (we might want to consider packing multiple matrices into a single h5 for convenience?), the big question is how to store/access them in memory.

Given our recent history with the `.loc` command I'm guessing storing zone_ids directly is basically a non-starter.  Fortunately, we're storing a dense matrix so we can make sure every zone_id is in position 1 greater than it's index (i.e. zone 1 is in index 0).  That way we can either 1) have a dataframe with a multi-index and call `.take` or 2) have a 2-D numpy array and access then directly, but only for one column at a time.  Do we think that 1) is slower than 2) because 1) is definitely more attractive from a code perspective.  I guess this "stacked" vs "unstacked" format.

At any rate, we should probably write a small abstraction to hide this from the user.  Basically we pass in one of the formats above with dimension N and then pass in two series of "origin" and "destination" zone ids and get back the values.

**Comment by fscottfoti** [comment]
Wanted to renew this thread as well.  A few separate issues...

* I'm not too concerned with the dense (square) vs sparse matrices issue.  Pandas has a `stack` and `unstack` operation which essentially transforms from one to the other if used with the appropriate indexes.  `stack` would go from dense to sparse and `unstack` would do the opposite.  For now we will do the square matrices but we will keep in mind that sparse matrices will be used when the matrices get too large.

* For the issue of storing one or more matrices per file, I think that's not too big a deal either.  hdf5 is a pretty lightweight file format - we can choose to put one matrix in there or multiple matrices in there for different use cases.  Generally, I can definitely see passing one matrix at a time from machine to machine, but if we end up using most of the matrices for the bottleneck of the model it might be convenient to store them together (it's essentially like a zip file, not really a format).

* As for the question of the assumption of whether zone_ids can be indexes (zero based and contiguous) it sounds like that is not guaranteed at all.  From a computational perspective though, it is required, so we will have a step at the beginning to convert labels to indexes, and for the early stages of the project we will assume that zone ids will be zero-based and contiguous (and that we'll have to fix that before we're through).

* My biggest concern is just how many skims will be necessary for which models, and if there are any ways to reduce memory or parallelize computation.  Generally we should get this working functionally first and we will keep an eye out for problems that can be made more efficient as we go.  It's likely these issues will come up again and again.

**Comment by guyrousseau** [comment]
Currently @ARC with CT-RAMP, in theory, the JPPF Driver application balances the load across the nodes so as to avoid the situation of machines sitting and waiting for others to finish.  However, the balancing algorithm depends upon the configuration of a set of parameters specified in the jppf properties files.  We have not had the opportunity to re-examine and fine-tune the settings since our new server was added to our cluster.  Similarly, the thread number settings could also be further tweaked.  So in our case, typically a single, best performing server, does a lot of the heavy lifting and probably handles 50% of the tasks. Thus, the workload being handled by each of the remaining machines (servers) probably does not justify the associated overhead relating to skim loading and task communications across the network.

**Comment by guyrousseau** [comment]
sorry I did not mean to close this thread of conversation
